# Generated by Django 2.1.2 on 2018-10-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_devices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devices',
            new_name='Device',
        ),
    ]
