# Generated by Django 2.1.2 on 2018-10-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20181028_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='rssi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
