# Generated by Django 2.1.2 on 2018-10-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20181028_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='measure_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
