# Generated by Django 2.1.2 on 2018-11-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_device_measure_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('state', models.BooleanField()),
                ('last_on_time', models.DateTimeField()),
                ('last_off_time', models.DateTimeField()),
            ],
        ),
    ]
