# Generated by Django 2.1.2 on 2018-11-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='last_off_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='last_on_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
