# Generated by Django 2.1.2 on 2018-12-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_auto_20181209_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='set_off_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
