# Generated by Django 2.1.2 on 2018-12-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_control_set_off_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='wan_ip',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
