# Generated by Django 2.1.2 on 2018-12-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0017_control_wan_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=64)),
                ('contact', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.CharField(blank=True, max_length=16)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
