# Generated by Django 2.1.2 on 2018-12-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0020_auto_20181226_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
