# Generated by Django 2.1.2 on 2018-12-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0021_auto_20181226_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='test/'),
        ),
    ]
