# Generated by Django 2.1.2 on 2018-12-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0023_offer_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='location_lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='location_lng',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
